import { StyleSheet } from "react-native";

const colors = {
  bg: "#181B1A",
  panel: "#1E2120",
  panelAlt: "#272A29",
  panelHover: "#222624",
  sidebar: "#141716",
  sidebarHover: "#1c1f1e",
  border: "#252B2A",
  borderAccent: "#2F3534",
  text: "#F3F5F4",
  textMuted: "#A1A5A4",
  textDim: "#6F7573",
  accent: "#20744A",
  accentBright: "#7CCBA0",
  danger: "#C64F43",
  warning: "#F59E0B",
  terminal: "#111413",
};

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg, paddingHorizontal: 16, paddingTop: 8, gap: 12 },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 28, height: 28 },
  brandTitle: { color: colors.text, fontSize: 18, fontWeight: "700", letterSpacing: 0.3 },
  spacer: { flex: 1 },
  statusDotWrap: { flexDirection: "row", alignItems: "center", gap: 6 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusDotSm: { width: 6, height: 6, borderRadius: 3 },
  statusLabel: { color: colors.textMuted, fontSize: 11, fontWeight: "600", textTransform: "uppercase" },
  serverId: { color: colors.textDim, fontSize: 12, marginTop: -6 },
  card: {
    width: "100%",
    maxWidth: 500,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 14,
    gap: 10,
    backgroundColor: colors.panel,
  },
  cardTitle: { color: colors.text, fontSize: 15, fontWeight: "600" },
  cardSub: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  input: {
    borderColor: colors.borderAccent,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    backgroundColor: colors.panelAlt,
    fontSize: 14,
  },
  inputGrow: { flex: 1 },
  inputRow: { flexDirection: "row", gap: 8, alignItems: "stretch" },
  btn: { backgroundColor: colors.accent, borderRadius: 8, minHeight: 42, justifyContent: "center", alignItems: "center", paddingHorizontal: 14 },
  btnDisabled: { opacity: 0.5 },
  btnText: { color: "#ffffff", fontWeight: "700", fontSize: 14 },
  btnDanger: { backgroundColor: colors.danger, borderRadius: 8, minHeight: 38, justifyContent: "center", alignItems: "center", flex: 1, paddingHorizontal: 12 },
  btnGhost: { borderRadius: 8, minHeight: 38, justifyContent: "center", alignItems: "center", flex: 1, borderWidth: 1, borderColor: colors.borderAccent, backgroundColor: colors.panelAlt, paddingHorizontal: 12 },
  ghostBtn: { minHeight: 36, justifyContent: "center", alignItems: "center", borderRadius: 8, borderWidth: 1, borderColor: colors.borderAccent, paddingHorizontal: 12, backgroundColor: colors.panelAlt },
  ghostBtnText: { color: colors.textMuted, fontWeight: "600", fontSize: 13 },
  iconBtn: { backgroundColor: colors.panelAlt, borderRadius: 8, minHeight: 42, justifyContent: "center", alignItems: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: colors.borderAccent },
  iconBtnText: { color: colors.text, fontWeight: "600", fontSize: 13 },
  linkBtn: { minHeight: 36, justifyContent: "center", alignItems: "center" },
  linkBtnText: { color: colors.textDim, fontSize: 13, fontWeight: "500" },
  error: { color: "#F0A39B", fontSize: 13, textAlign: "center" },
  top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  agentHead: { gap: 4 },
  agentTitle: { color: colors.text, fontSize: 22, fontWeight: "700" },
  agentMeta: { color: colors.textMuted, fontSize: 13 },
  list: { flex: 1 },
  agentRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 12, marginBottom: 8, backgroundColor: colors.panel, gap: 4 },
  agentRowTop: { flexDirection: "row", alignItems: "center", gap: 8 },
  agentRowTitle: { color: colors.text, fontWeight: "600", fontSize: 14 },
  agentRowMeta: { color: colors.textMuted, fontSize: 12 },
  agentRowCwd: { color: colors.textDim, fontSize: 11 },
  timeline: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 8, backgroundColor: colors.panel },
  event: { flexDirection: "row", gap: 8, marginBottom: 10 },
  eventSeq: { color: colors.accentBright, fontSize: 11, fontWeight: "700", width: 36 },
  eventBody: { flex: 1, gap: 2 },
  eventType: { color: colors.textMuted, fontSize: 11, fontWeight: "600", textTransform: "uppercase" },
  eventText: { color: colors.text, fontSize: 13, lineHeight: 18 },
  empty: { color: colors.textDim, fontSize: 13, textAlign: "center", paddingVertical: 20 },
  actionRow: { flexDirection: "row", gap: 8 },
  qrImage: { width: 256, height: 256, alignSelf: "center", borderRadius: 12, backgroundColor: "#ffffff" },
  qrUrl: { color: colors.textMuted, fontSize: 11 },
  sectionTitle: { color: colors.text, fontSize: 12, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.8 },
  workspaceRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 12, backgroundColor: colors.panelAlt, gap: 4 },
  workspaceRowActive: { borderColor: colors.accent, backgroundColor: colors.panelHover },
  workspaceName: { color: colors.text, fontWeight: "700", fontSize: 14 },
  workspaceMeta: { color: colors.textMuted, fontSize: 12 },
  workspaceProject: { color: colors.textDim, fontSize: 11 },
  terminalOutput: {
    minHeight: 140,
    maxHeight: 260,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.terminal,
    padding: 10,
  },
  terminalText: { color: "#DCE2DF", fontSize: 12, lineHeight: 16, fontFamily: "monospace" },

  shell: { flex: 1, width: "100%", maxWidth: 1500, alignSelf: "center", gap: 12 },
  shellHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.panel,
  },
  shellHeaderMeta: { gap: 2, flex: 1 },
  shellTitle: { color: colors.text, fontSize: 18, fontWeight: "700" },
  shellSubtitle: { color: colors.textMuted, fontSize: 12 },
  shellBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    backgroundColor: colors.panelAlt,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  shellBadgeText: { color: colors.textMuted, fontSize: 11, fontWeight: "700", textTransform: "uppercase" },
  shellBody: { flex: 1, flexDirection: "row", gap: 12, minHeight: 0 },
  leftSidebar: {
    width: 308,
    backgroundColor: colors.sidebar,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 12,
  },
  centerPane: { flex: 1, gap: 12, minWidth: 0 },
  rightRail: { width: 360, gap: 12 },
  sidebarSection: { gap: 8 },
  sidebarSectionTitle: { color: colors.textMuted, fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.8 },
  sidebarItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 10,
    gap: 3,
  },
  sidebarItemActive: {
    borderColor: colors.accent,
    backgroundColor: colors.panelHover,
  },
  sidebarItemTitle: { color: colors.text, fontSize: 13, fontWeight: "700" },
  sidebarItemMeta: { color: colors.textMuted, fontSize: 11 },
  sidebarItemPath: { color: colors.textDim, fontSize: 10 },
  agentListWrap: { flex: 1, minHeight: 0 },
  primaryPanel: {
    backgroundColor: colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    gap: 12,
  },
  panelHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  panelHeaderStack: { gap: 4, flex: 1 },
  panelTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
  panelSub: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  segmentedRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  segmentedChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    backgroundColor: colors.panelAlt,
  },
  segmentedChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  segmentedChipText: { color: colors.textMuted, fontSize: 12, fontWeight: "700" },
  segmentedChipTextActive: { color: "#ffffff" },
  formGrid: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  formField: { flex: 1, minWidth: 180, gap: 6 },
  formFieldWide: { width: "100%", gap: 6 },
  fieldLabel: { color: colors.textMuted, fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.6 },
  mainGrid: { flexDirection: "row", gap: 12, minHeight: 0 },
  stackColumn: { flex: 1, gap: 12, minWidth: 0 },
  utilityCard: {
    backgroundColor: colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 10,
  },
  miniCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.panelAlt,
    padding: 10,
    gap: 4,
  },
  miniCardTitle: { color: colors.text, fontSize: 13, fontWeight: "700" },
  miniCardMeta: { color: colors.textMuted, fontSize: 11 },
  scrollArea: { flex: 1, minHeight: 0 },
  detailShell: { flex: 1, width: "100%", maxWidth: 1500, alignSelf: "center", gap: 12 },
  detailBody: { flex: 1, flexDirection: "row", gap: 12, minHeight: 0 },
  detailRail: {
    width: 320,
    backgroundColor: colors.sidebar,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    gap: 10,
  },
  detailMain: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    gap: 12,
  },
});
